# Ask user what drink do they prefer
print(" 1. What soft drink would you like?: ")
print()
print("  a. Doke")
print()
print("  b. Bepsi")
print()
print("  c. Sahara Haze ")
print()
print("  d. Dr. Salt")
print()
drink = input("What drink would you prefer?: ") 
print("===============")
# Ask user what size would they like 
print(" 2. What size would you like?:  ") 
print()
print("  a. 8oz") 
print()
print("  b. 16oz") 
print()
print("  c. 24oz") 
print() 
print("  d. 32oz")
print()
size = input("What size would like?:  ")
print("================")
# Ask user would they like ice 
print(" 3. Would you like ice?: ") 
print()
ice = input("Please answer 'yes', 'no': ").capitalize()
print()
print(ice)
print("=================")
# Ask user how much ice would they like
print(" 4. How much ice would you like today?: ")
print()
print("  a. Alot of ice!!!")
print()
print("  b. some ice ") 
print()
print("  c. light ice ")
print()
print("  d. I already told you I don't want ice!!!! ")
print()
a = input("Please how much ice would you prefer?: ")
print("=================")
# Ask user would they like regular or diet 
t = input(" 5. Would you like your drink to be regular or diet?: ").capitalize()
print(t) 
print("==================")
# Ask the customer would they like a receipt
print("  6. Would you like a receipt today?: ")
print()
r = input("'yes, or no': " ).capitalize() 
print()
print(r) 
# Display summary of transaction to customer 
print("Summary of today's transaction!!!: ") 
print()
print(f"Drink selected: {drink}")
print()
print(f"Size selected: {size}") 
print() 
print(f"Was ice selected?: {ice}")
print() 
print(f"How much ice was selected?: {a}")
print()
print(f"Drink type selected: {t}")
print()
print(f"Did the customer ask for receipt: {r}")